language: ruby
rvm:
- 2.4.1
services:
- postgresql
before_script:
- psql -c 'create database koroibos_test;' -U postgres
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: FCAnLDFCPBx+dhUHLjwFzu5KhGHRpEmWFFrlzbGdvkpGsmUq0GH6ALtSV3akGv8C1Adz8hUbu9VTJ+gmNa8bcRc266IqqWC50aZNi84fXhGadHmDAfGwgtA/aBqGZHdD9pyPG6mId7mpE+y0KxMvd4Gw52FsL9GnPAST0PdJ3lF6mwYOK/Ajfu+faDRo2jLsuTg91/nKT6NW+8AzlW5aWyFO3LbEKRDmzvr7k2Dvq08Da78hZekekCG6cxDHbrgkz1sTYUkQF/e7G+PoiHoR6+Yr1If5qRDjsXsIhGabV0RWMlqILlYoRbCd9nCixgduMaIsoKfmQPn+Wm0mjt3FSnHqC4QtiaBGwcugdINaifSFYsPvBYRDty27+Cml0EMMlmrHEUkizVz8c86gxMqbJtmnkjrAi5HfB6RuMRVb+3AzQaliAbgk00/OSMjnXWjp3gCxvPPqAb9h22cLe/SrxfC/sevekulAEB6PaiOssXYOvnNBWhrTb87Tr9MJOf7m2/S51Gym6gn7GUnkuDY4KubgvGI7aEBdhtdzVIRtfrYG6NhewhkD0y//hwRIr/EfNGLh40btvBtRSP42JyggK/wrT6XWECTNTDg+KlZ0W2ZGTk3FtjENYxHe69uuJ3Ye6RrclxQnql1sTAQMeaq3Q/HlN2LoPwNmj3e8pUQWpS8=
  app: pacific-inlet-44351
  on:
    repo: zacisaacson/koroibos
