language: ruby
rvm:
- 2.4.1
services:
- postgresql
before_script:
- psql -c 'create database koroibos_test;' -U postgres
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: CG2J4mbnzeCq93Fid8LfbESZgdx4digHD19DD9YxDFLDbW+LiGGyGcie/mc4hEyMAOicHeOkmUtD0cULtdnaIf45tgR7GmbXrGvqh2b75twz5UyUQdF7csK0jH5XlzkQsAvQwo0f/vuJQRdv/sukeyiBukoPv3RxixFRi5WSFpoFJsuqm7q9DaDO+V/AY6xNd35PaHm9RzFJysniBNo+l3lXAwQP8CiQ7JamQ5Jn6o2VXX8hlhPgXNonCt9bpiXiWyCM2XCG5sV1VMOEDp3FBsu+EjRwfJ+tLd8HdVvM/l0PCvhrwIbwpJpwG59sG0DUevfAwbetRPuvgsydW+0jTkM/SwlcBHnNWcQO82lQ0BpFQfKLJu+igjno5l5wfX2eOdLtA6h3nK02zz8g2uY+PRkS/ak2ggvgWO48eVEg51zDlV8+091Vqu+eWOBJ8elzYonB6sfPmhWSYbg1IcIHPuvyatZ3ZLtffkicZBbWVk2dzi4hTD0NND61naT+lUPdDVos66YC833SYXhXEoqkJzfcaLyLl6zkdfQ/YeEUxn4NzeRw9wU6IDnk6Woc4wIVi9u5SlA9egSDsP1dH0IOienW1TXYnpng5sbS8AL8EZjtwo8d1VwoNoupvkDI6/K4ibsAJnrEgSPcvfrwqOIzTnnCWn8RP/GMkVHO51mmkZk=
  app: pacific-inlet-44351
