language: ruby
rvm:
- 2.4.1
services:
- postgresql
before_script:
- psql -c 'create database koroibos_test;' -U postgres
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: mhMscNBOk2MYkzm2rXiEhOUswuMLUhsBHaxT0l0fGK72bLyxqwwzXu9Iib+uHdBAzLYsRlVbXCOO6vnBIlVKBXzC66nd9nA1nUj/GpBWGk+sepwbAIFcKhHwEVMJeD95DcWzQPVXfZIoE22k2Ml+lSvRw5o3p7ZDcgnsbOGqKZ39xmCWYfLW2sqvuVSKweXQXwGml8d9gUytjyHCH4Mmy7mhSowWYxfCo+XTq7pwcQ0A8sJACOzK9YicbtvQlE6qznwTvsMgYxRzg4+PfyB6q8bYWubZUhznxxvZ8XRVLzlpZyq+bGRoQlpQZb5sPbb92d+lIoBCDIY2CS8rPGVFRy/Md6pv8aFE0fUdtu1xBH3V/8HkNDuXBsrSBswPVnYlsflfnsA94mJdWbijCh3vzNUjJvF38IaBMYRSaLAXkFCsfOU7Zhhq4/nLb3W6ZjbST/C6+t+0K5tYznptRKvAGl9B/HSOdKwtvjPu5BffoN572FELKMsX0pGk0yp94ryEhbedKHJC1TBZesCjwWnBo/1dQO430N4glXOQi86OLRB6Klvfg6aTTp/U+vHdOF7lVdxHNj6LZimLU97hEjSm3VqUuKePe1DRhqsGVteS732nLvRoIDQQ/h05ye1TW7x02yNHgNHM8zCjnyhIhfsZAlLcrLzeOYLEA0LfgEyIWu4=
  app: koroibos-api
  on:
    repo: zacisaacson/koroibos
